### PR TITLE
Qvs as uint8

### PR DESCRIPTION
**Pull request by pezmaster31**

### CODE REVIEW

**Comment by armintoepfer** [comment]
+1

**Comment by dalexander** [comment]
This change is a good idea but could cause a lot of upheaval.  

From the python side, I can say that I have been waiting for the release of pysam 0.8.4, which will finally make it efficient to access arrays in tags.  It has not been released yet, which means that pbcore-based consumers of the component QVs (Quiver, primarily) will get substantially slower (in pysam 0.8.3 it takes about 300x as long to grab a uint8[] from a BAM as it does to grab a string of the same length).

There would also be a lot of upheaval in the C++ side of things.

Not to mention that we would no longer be able to "patch"---every file we have would have to be rebuilt.

**Comment by dalexander** [comment]
More thoughts:  given Nigel's recent modeling, we are pretty close to saying that the component QVs are totally unnecessary.  So perhaps the better idea is just to ditch them entirely; this is pending analyses to ascertain that the multimolecule Arrow model is at least as good as Quiver.

@evolvedmicrobe @nlhepler

**Comment by evolvedmicrobe** [comment]
I think it will always be true that some additional information can help us improve accuracy at low coverage, so some QV information will likely be useful.  Though for our current use cases I don't think these are.  I would say it would make sense to hold off on this until we establish what information we will use and how we will use it (unless the current patch would do anything other than make the python code slow, not sure what motivated this originally)

**Comment by armintoepfer** [comment]
Getting rid of the QVs would allow us to give you pulseWidth in production mode.

**Comment by dalexander** [comment]
I think we should hold off on this patch, instead just let's put the burden on the QV-producing code to respect the dynamic range requirement for FASTQ-style encoding ... and then when we have more information we can revisit the possibility of ditching these QVs and tags... possibly introducing a new tag for some covariate of interest to Nigel.

**Pull request closed without merging**
