### PR TITLE
Proposed changes to Barcode representation in the Header/PBI

### PR DESCRIPTION
**Pull request by bnbowman**
-BarcodeQuality element added to BAM DS tag
-Separate Adapter/Barcode rep in PBI
-Convert PBI BC-tag value to signed for representing non-existant values
-Clarify the required existence of empty columns in the PBI for ease of access/understanding

### CODE REVIEW

**Comment by dalexander** [comment]
I am ok with that if necessary, though I think the precedent is that the pbi doesn't have to be fully self-contained---it is already somewhat expected that the BAM headers have to be cross-referenced to make sense of some of the values in the pbi.  For example, to turn a reference contig key (integer) into the actual contig name, you have to xref the BAM header.

**Comment by dalexander** [comment]
@bnbowman, @mdsmith : this needs to be finalized _today_ or it is not getting into 3.0b8 (and therefore 3.0)

**Comment by bnbowman** [comment]
Updated my Pull request.

Also had a thought - we need to be able to index all valid forms of PacBio BAM files - including HQRegion only and Polymerase-Read files, which won't have CX tags.  So the proposal to drop the Adapter flag and make the CX tags mandatory don't make sense.

**Comment by dalexander** [comment]
This looks pretty good, though I think I may change "Record data" to "Basic data"

**Pull request merged**
