### PR TITLE
Add @RG::PM ("platform model") to indicate instrument generation (AST…

### PR DESCRIPTION
**Pull request by dalexander**
…RO, RS, SEQUEL)

Bump version spec to 3.0.2 accordingly

### CODE REVIEW

**Comment by dalexander** [comment]
@pezmaster31 @armintoepfer

**Comment by pezmaster31** [comment]
looks good to me

**Comment by pezmaster31** [comment]
unrelated, i kinda feel sorry for poor github user RG ... getting tagged in so many SAM/BAM commits

**Comment by dalexander** [comment]
Yeah, sorry Rohit @RG!  

Anyway, I will merge.  The version bump seems like a small deal to me but is pro-forma.

**Pull request merged**
