### PR TITLE
Change rq from integer to float, note that READTYPE=CCS will have QUA…

### PR DESCRIPTION
**Pull request by nlhepler**
…L values

### CODE REVIEW

**Comment by dalexander** [comment]
hmm, how can i merge this to a new branch instead

**Comment by dalexander** [comment]
OK boo on github:  https://github.com/isaacs/github/issues/18

**Comment by nlhepler** [comment]
I can push it into a topic branch if you would like, directly.

**Comment by nlhepler** [comment]
https://github.com/PacificBiosciences/PacBioFileFormats/tree/RQFloat

**Comment by dalexander** [comment]
OK thanks I got it now

https://github.com/PacificBiosciences/PacBioFileFormats/tree/3.0.8

**Pull request closed without merging**
