### PR TITLE
Adding Tailed barcodes to the BAM spec

### PR DESCRIPTION
**Pull request by bnbowman**
For support for the new Universal Barcode protocol

### CODE REVIEW

**Comment by bnbowman** [comment]
For reference, this is for Bug #30421

**Comment by bnbowman** [comment]
My preference was "paired" for our "asymmetric" mode (since we are _pairing_ two barcodes) and "asymmetric" for this new mode (since it uses normal barcodes _asymmetrically_), but this is the lingo that SMS uses and doesn't require re-educating anyone..

**Comment by dalexander** [comment]
OK I am merging.   I would like us to create a "primer" document in this repo that explains the different sample prep configurations.  PPA has a document that we can copy to some degree.

**Comment by bnbowman** [comment]
Working with Jharting to update the bifx wiki to do just that

**Pull request merged**
